version: '3'

services:
  redis:
    image: "redis:latest"
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - mynetwork
    volumes:
      - redis-data:/data


  postgres:
    image: "postgres:latest"
    container_name: postgres
    ports:
      - "5432:5432"
    networks:
      - mynetwork
    environment:
      POSTGRES_DB: db_name
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: db_passwd
    volumes:
      - postgres-data:/var/lib/postgresql/data


  mosquitto:
    image: "eclipse-mosquitto:latest"
    container_name: mosquitto
    networks:
      - mynetwork
    ports:
      - "1883:1883"


  db_handler:
    build:
      context: .
      dockerfile: DbHandler/Dockerfile
    container_name: DbHandler
    networks:
      - mynetwork
    depends_on:
      - redis
      - postgres
      - mosquitto  


  # mqtt_handler:
  #   build:
  #     context: ./MqttHandler
  #     dockerfile: Dockerfile
  #   container_name: MqttHandler
  #   networks:
  #     - mynetwork
  #   depends_on:
  #     - redis
  #     - postgres
  #     - mosquitto  


  # web_app:
  #   build:
  #     context: ./WebApp
  #     dockerfile: Dockerfile
  #   container_name: WebApp
  #   ports:
  #     - "5000:5000"
  #   networks:
  #     - mynetwork
  #   depends_on:
  #     - redis
  #     - postgres
  #     - mosquitto

networks:
  mynetwork:
    driver: bridge

volumes:
  redis-data:
  postgres-data:
