version: '3'

services:
  redis:
    image: "redis:latest"
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - mynetwork
    volumes:
      - redis-data:/data

  postgres:
    image: "postgres:latest"
    container_name: postgres
    ports:
      - "5432:5432"
    networks:
      - mynetwork
    environment:
      POSTGRES_DB: db_name
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: db_passwd
    volumes:
      - postgres-data:/var/lib/postgresql/data

  flask-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flaskapp
    ports:
      - "5000:5000"
    networks:
      - mynetwork
    depends_on:
      - redis
      - postgres

networks:
  mynetwork:
    driver: bridge

volumes:
  redis-data:
  postgres-data:
