version: '3'

services:
  redis:
    image: "redis:latest"
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      docker_net:
        ipv4_address: 172.42.0.10
    volumes:
      - redis-data:/data


  mosquitto:
    image: "eclipse-mosquitto:latest"
    container_name: mosquitto
    networks:
      docker_net:
        ipv4_address: 172.42.0.11
    ports:
      - "1883:1883"
    depends_on:
      - redis


  db_handler:
    build:
      context: .
      dockerfile: DbHandler/Dockerfile
    container_name: DbHandler
    networks:
      - ext_net
      - docker_net
    depends_on:
      - redis
      - mosquitto  


  mqtt_handler:
    build:
      context: .
      dockerfile: MqttHandler/Dockerfile
    container_name: MqttHandler
    networks:
      - docker_net
    depends_on:
      - redis
      - mosquitto  


  web_app:
    build:
      context: .
      dockerfile: WebApp/Dockerfile
    container_name: WebApp
    ports:
      - "5000:5000"
    networks:
      - docker_net
    depends_on:
      - redis
      - mosquitto

networks:
  docker_net:
    driver: bridge
    external: true
    # ipam:
    #   config:
    #     - subnet: 172.42.0.0/16
    #       gateway: 172.42.0.1
  ext_net:
    external: true

volumes:
  redis-data:
  # postgres-data:
